export interface Listing {
  listingid:number;
  storeid:number;
  title:string;
  category:string;
  images:string;
  description:string;
  price:number;
  tags:string;
  materials:string;
  shopsectionid:string;
  url:string;
  views:string;
  numfavourers:string;
  whenmade:string;
  weight:string;
  length:string;
  width:string;
  height:string;
  used:string;
}
